name: Novo SGA
markdown: redcarpet
pygments: true
locale: pt
locales: 
  pt:
    nav:
      home: Home
      projects: Projetos
      downloads: Downloads
      faq: FAQ
      community: Comunidade
      about: Sobre
    home:
      title: Novo, rápido e moderno!
      text: Sistema de Gerenciamento de Atendimento de código aberto e gratuito.
      see_more: Ver mais
      about:
        title: Sobre
        text: Novo SGA não é um simples projeto e sim uma plataforma para gerenciamento de atendimento.
      projects:
        title: Projetos
        text: Conheça os projetos que fazem parte da plataforma Novo SGA.
      support:
        title: Suporte
        text: Dúvidas? Visite a seção FAQ do site, ou acesse um dos canais de comunicação da comunidade.
        
    downloads:
      title: Downloads
      text: |
            <p>A partir da versão 1.0.0 os componentes Desktops (Java/JavaFX) não são mais compatíveis com o Novo SGA. No lugar destes, você pode usar as implementações em HTML.</p>
            <p>Então caso, queira utilizar ou esteja utilizando uma implementação Desktop, opte por baixar uma das versões 0.X.X.</p>
      last:
        title: Última versão estável
        text: |
              <p>Baixe agora a última versão estável através do nosso repositório no Github.</p>
        novosga: |
                 <p>Projeto principal.</p>
        painelweb: |
                   <p>Painel escrito em HTML5 e Javascript.</p>
        triagemtouch: |
                      <p>Triagem voltada para telas sensíveis ao toque.</p>
      others:
        title: Outras versões
        text: |
              <p>Versões anteriores (até 0.7.2). Pacotes disponíveis: novosga-web, novosga-painel-client (PainelFX) e novosga-painel-server.</p>
        version: Versão
        painelfx: Painel Cliente (PainelFX)
        server: Painel Servidor
      demo:
        title: Demonstração
        text: |
              <p>Versão de desenvolvimento disponível online através do link: <a href="http://novosga.org/demo">http://novosga.org/demo</a></p>
        user: Usuário
        pass: Senha
        
    projects:
      title: Projetos
      download: Download
      view: Visitar
      novosga:
        text: |
              <p>Projeto principal, divido em módulos.</p>
              <p>Módulos principais (pré-instalados):</p>
              <ul>
                  <li>Triagem (emissão de senha)</li>
                  <li>Monitor (gerenciamento)</li>
                  <li>Atendimento</li>
              </ul>
      painelweb:
        text: |
              <p>Implementação do painel de exibição de senhas escrito em HTML5 e Javascript.</p>
              <p>Compatível com versões do Novo SGA a partir da 1.0.0</p>
      triagemtouch:
        text: |
              <p>Implementação da Triagem para auto-atendimento em telas sensíveis ao toque.</p>
              <p>Compatível com versões do Novo SGA a partir da 1.0.0</p>
      painelfx:
        text: |
              <p>Implementação do painel de exibição de senhas escrito em JavaFX (JRE1.7+). Depende do servidor de painel para funcionar.</p>
              <p>Compatível até a versão 0.7.2 do Novo SGA.</p>
      painelserver:
        text: |
              <p>Processo escrito em Java para disparar as senhas via UDP ou TCP para os painéis (desktop) cadastrados.</p>
              <p>Compatível até a versão 0.7.2 do Novo SGA.</p>
              
    about:
      title: Sobre
      text: |
            <p>SGA é o acrônimo de Sistema de Gerenciamento de Atendimento, e Novo SGA é uma plataforma de código aberto que permite grandes ou pequenas organizações gerenciarem o fluxo do atendimento.</p>
            <p>Criado em Dezembro de 2012 por <a href="http://rogeriolino.com">Rogério Alencar Lino Filho</a>, o Novo SGA provê funcionalidades para controlar a ordem da fila de atendimento e os tempos para atender (hora de chegada, tempo de espera, tempo de deslocamento até o balcão e tempo de atendimento), além de fornecer gráficos e estatísticas para aprimorar o atendimento ao cliente.</p>
      features:
        title: Funcionalidades
        text: |
              <ul>
                  <li>Emissão de senhas normais ou prioritárias</li>
                  <li>Cancelamento, reativação e transferência de senha</li>
                  <li>Configuração de tipo de atendimento por guichê</li>
                  <li>Monitoramento das filas por serviços</li>
                  <li>Númeração incremental por sigla de serviço ou global</li>
                  <li>Gráficos e relatórios</li>
              </ul>
      screenshots:
        title: Screenshots
        prints: 
          - PainelFX
          - PainelFX - Screensaver
          - PainelFX - Configuração
          - PainelFX - Configuração
          - Login
          - Escolhendo unidade
          - Página Inicial
          - Perfil do usuário
          - Configuração da Unidade
          - Configuração da Unidade
          - Triagem
          - Triagem
          - Monitor de senhas
          - Monitor de senhas
          - Monitor de senhas
          - Atendimento
          - Atendimento
          - Atendimento
          - Atendimento
          
    community:
      title: Comunidade
      text: |
            <p>Ajuda a comunidade do Novo SGA continuar crescendo. Participe nos canais de comunicação e faremos um sistema cada vez melhor.</p>
      view: Visite
      blog:
        title: Blog
        text: |
              <p>Fique sabendo das novidades sobre o Novo SGA através do blog do projeto.</p>
              <p>A partir dele publicamos as notícias sobre versões lançadas, versões futuras e dicas.</p>
      forum:
        title: Fórum
        text: |
              <p>Tire suas dúvidas, ou ajude a sanar as dúvidas de outros usuários, nos fóruns dos projetos ou contribua com dicas e showcase.</p>
      dev:
        title: Desenvolvimento
        text: |
              <p>Quer participar do desenvolvimento? Então cadastre-se no <a href="http://github.com">Github</a> e crie logo o seu fork.</p>
      
      
  en:
    nav:
      home: Home
      projects: Projects
      downloads: Downloads
      faq: FAQ
      community: Community
      about: About
    home:
      title: Novo, rápido e moderno!
      text: Sistema de Gerenciamento de Atendimento de código aberto e gratuito.
      see_more: Ver mais
      about:
        title: Sobre
        text: Novo SGA não é um simples projeto e sim uma plataforma para gerenciamento de atendimento.
      projects:
        title: Projetos
        text: Conheça os projetos que fazem parte da plataforma Novo SGA.
      support:
        title: Suporte
        text: Dúvidas? Visite a seção FAQ do site, ou acesse um dos canais de comunicação da comunidade.
        
    downloads:
      title: Downloads
      text: |
            <p>A partir da versão 1.0.0 os componentes Desktops (Java/JavaFX) não são mais compatíveis com o Novo SGA. No lugar destes, você pode usar as implementações em HTML.</p>
            <p>Então caso, queira utilizar ou esteja utilizando uma implementação Desktop, opte por baixar uma das versões 0.X.X.</p>
      last:
        title: Última versão estável
        text: |
              <p>Baixe agora a última versão estável através do nosso repositório no Github.</p>
        novosga: |
                 <p>Projeto principal.</p>
        painelweb: |
                   <p>Painel escrito em HTML5 e Javascript.</p>
        triagemtouch: |
                      <p>Triagem voltada para telas sensíveis ao toque.</p>
      others:
        title: Outras versões
        text: |
              <p>Versões anteriores (até 0.7.2). Pacotes disponíveis: novosga-web, novosga-painel-client (PainelFX) e novosga-painel-server.</p>
        version: Versão
        painelfx: Painel Cliente (PainelFX)
        server: Painel Servidor
      demo:
        title: Demonstração
        text: |
              <p>Versão de desenvolvimento disponível online através do link: <a href="http://novosga.org/demo">http://novosga.org/demo</a></p>
        user: Usuário
        pass: Senha
        
    projects:
      title: Projetos
      download: Download
      view: Visitar
      novosga:
        text: |
              <p>Projeto principal, divido em módulos.</p>
              <p>Módulos principais (pré-instalados):</p>
              <ul>
                  <li>Triagem (emissão de senha)</li>
                  <li>Monitor (gerenciamento)</li>
                  <li>Atendimento</li>
              </ul>
      painelweb:
        text: |
              <p>Implementação do painel de exibição de senhas escrito em HTML5 e Javascript.</p>
              <p>Compatível com versões do Novo SGA a partir da 1.0.0</p>
      triagemtouch:
        text: |
              <p>Implementação da Triagem para auto-atendimento em telas sensíveis ao toque.</p>
              <p>Compatível com versões do Novo SGA a partir da 1.0.0</p>
      painelfx:
        text: |
              <p>Implementação do painel de exibição de senhas escrito em JavaFX (JRE1.7+). Depende do servidor de painel para funcionar.</p>
              <p>Compatível até a versão 0.7.2 do Novo SGA.</p>
      painelserver:
        text: |
              <p>Processo escrito em Java para disparar as senhas via UDP ou TCP para os painéis (desktop) cadastrados.</p>
              <p>Compatível até a versão 0.7.2 do Novo SGA.</p>
              
    about:
      title: Sobre
      text: |
            <p>SGA é o acrônimo de Sistema de Gerenciamento de Atendimento, e Novo SGA é uma plataforma de código aberto que permite grandes ou pequenas organizações gerenciarem o fluxo do atendimento.</p>
            <p>Criado em Dezembro de 2012 por <a href="http://rogeriolino.com">Rogério Alencar Lino Filho</a>, o Novo SGA provê funcionalidades para controlar a ordem da fila de atendimento e os tempos para atender (hora de chegada, tempo de espera, tempo de deslocamento até o balcão e tempo de atendimento), além de fornecer gráficos e estatísticas para aprimorar o atendimento ao cliente.</p>
      features:
        title: Funcionalidades
        text: |
              <ul>
                  <li>Emissão de senhas normais ou prioritárias</li>
                  <li>Cancelamento, reativação e transferência de senha</li>
                  <li>Configuração de tipo de atendimento por guichê</li>
                  <li>Monitoramento das filas por serviços</li>
                  <li>Númeração incremental por sigla de serviço ou global</li>
                  <li>Gráficos e relatórios</li>
              </ul>
      screenshots:
        title: Screenshots
        prints: 
          - PainelFX
          - PainelFX - Screensaver
          - PainelFX - Configuração
          - PainelFX - Configuração
          - Login
          - Escolhendo unidade
          - Página Inicial
          - Perfil do usuário
          - Configuração da Unidade
          - Configuração da Unidade
          - Triagem
          - Triagem
          - Monitor de senhas
          - Monitor de senhas
          - Monitor de senhas
          - Atendimento
          - Atendimento
          - Atendimento
          - Atendimento
          
    community:
      title: Comunidade
      text: |
            <p>Ajuda a comunidade do Novo SGA continuar crescendo. Participe nos canais de comunicação e faremos um sistema cada vez melhor.</p>
      view: Visite
      blog:
        title: Blog
        text: |
              <p>Fique sabendo das novidades sobre o Novo SGA através do blog do projeto.</p>
              <p>A partir dele publicamos as notícias sobre versões lançadas, versões futuras e dicas.</p>
      forum:
        title: Fórum
        text: |
              <p>Tire suas dúvidas, ou ajude a sanar as dúvidas de outros usuários, nos fóruns dos projetos ou contribua com dicas e showcase.</p>
      dev:
        title: Desenvolvimento
        text: |
              <p>Quer participar do desenvolvimento? Então cadastre-se no <a href="http://github.com">Github</a> e crie logo o seu fork.</p>
      
  es:
    nav:
      home: Home
      projects: Projects
      downloads: Downloads
      faq: FAQ
      community: Community
      about: About
    home:
      title: Novo, rápido e moderno!
      text: Sistema de Gerenciamento de Atendimento de código aberto e gratuito.
      see_more: Ver mais
      about:
        title: Sobre
        text: Novo SGA não é um simples projeto e sim uma plataforma para gerenciamento de atendimento.
      projects:
        title: Projetos
        text: Conheça os projetos que fazem parte da plataforma Novo SGA.
      support:
        title: Suporte
        text: Dúvidas? Visite a seção FAQ do site, ou acesse um dos canais de comunicação da comunidade.
        
    downloads:
      title: Downloads
      text: |
            <p>A partir da versão 1.0.0 os componentes Desktops (Java/JavaFX) não são mais compatíveis com o Novo SGA. No lugar destes, você pode usar as implementações em HTML.</p>
            <p>Então caso, queira utilizar ou esteja utilizando uma implementação Desktop, opte por baixar uma das versões 0.X.X.</p>
      last:
        title: Última versão estável
        text: |
              <p>Baixe agora a última versão estável através do nosso repositório no Github.</p>
        novosga: |
                 <p>Projeto principal.</p>
        painelweb: |
                   <p>Painel escrito em HTML5 e Javascript.</p>
        triagemtouch: |
                      <p>Triagem voltada para telas sensíveis ao toque.</p>
      others:
        title: Outras versões
        text: |
              <p>Versões anteriores (até 0.7.2). Pacotes disponíveis: novosga-web, novosga-painel-client (PainelFX) e novosga-painel-server.</p>
        version: Versão
        painelfx: Painel Cliente (PainelFX)
        server: Painel Servidor
      demo:
        title: Demonstração
        text: |
              <p>Versão de desenvolvimento disponível online através do link: <a href="http://novosga.org/demo">http://novosga.org/demo</a></p>
        user: Usuário
        pass: Senha
        
    projects:
      title: Projetos
      download: Download
      view: Visitar
      novosga:
        text: |
              <p>Projeto principal, divido em módulos.</p>
              <p>Módulos principais (pré-instalados):</p>
              <ul>
                  <li>Triagem (emissão de senha)</li>
                  <li>Monitor (gerenciamento)</li>
                  <li>Atendimento</li>
              </ul>
      painelweb:
        text: |
              <p>Implementação do painel de exibição de senhas escrito em HTML5 e Javascript.</p>
              <p>Compatível com versões do Novo SGA a partir da 1.0.0</p>
      triagemtouch:
        text: |
              <p>Implementação da Triagem para auto-atendimento em telas sensíveis ao toque.</p>
              <p>Compatível com versões do Novo SGA a partir da 1.0.0</p>
      painelfx:
        text: |
              <p>Implementação do painel de exibição de senhas escrito em JavaFX (JRE1.7+). Depende do servidor de painel para funcionar.</p>
              <p>Compatível até a versão 0.7.2 do Novo SGA.</p>
      painelserver:
        text: |
              <p>Processo escrito em Java para disparar as senhas via UDP ou TCP para os painéis (desktop) cadastrados.</p>
              <p>Compatível até a versão 0.7.2 do Novo SGA.</p>
              
    about:
      title: Sobre
      text: |
            <p>SGA é o acrônimo de Sistema de Gerenciamento de Atendimento, e Novo SGA é uma plataforma de código aberto que permite grandes ou pequenas organizações gerenciarem o fluxo do atendimento.</p>
            <p>Criado em Dezembro de 2012 por <a href="http://rogeriolino.com">Rogério Alencar Lino Filho</a>, o Novo SGA provê funcionalidades para controlar a ordem da fila de atendimento e os tempos para atender (hora de chegada, tempo de espera, tempo de deslocamento até o balcão e tempo de atendimento), além de fornecer gráficos e estatísticas para aprimorar o atendimento ao cliente.</p>
      features:
        title: Funcionalidades
        text: |
              <ul>
                  <li>Emissão de senhas normais ou prioritárias</li>
                  <li>Cancelamento, reativação e transferência de senha</li>
                  <li>Configuração de tipo de atendimento por guichê</li>
                  <li>Monitoramento das filas por serviços</li>
                  <li>Númeração incremental por sigla de serviço ou global</li>
                  <li>Gráficos e relatórios</li>
              </ul>
      screenshots:
        title: Screenshots
        prints: 
          - PainelFX
          - PainelFX - Screensaver
          - PainelFX - Configuração
          - PainelFX - Configuração
          - Login
          - Escolhendo unidade
          - Página Inicial
          - Perfil do usuário
          - Configuração da Unidade
          - Configuração da Unidade
          - Triagem
          - Triagem
          - Monitor de senhas
          - Monitor de senhas
          - Monitor de senhas
          - Atendimento
          - Atendimento
          - Atendimento
          - Atendimento
          
    community:
      title: Comunidade
      text: |
            <p>Ajuda a comunidade do Novo SGA continuar crescendo. Participe nos canais de comunicação e faremos um sistema cada vez melhor.</p>
      view: Visite
      blog:
        title: Blog
        text: |
              <p>Fique sabendo das novidades sobre o Novo SGA através do blog do projeto.</p>
              <p>A partir dele publicamos as notícias sobre versões lançadas, versões futuras e dicas.</p>
      forum:
        title: Fórum
        text: |
              <p>Tire suas dúvidas, ou ajude a sanar as dúvidas de outros usuários, nos fóruns dos projetos ou contribua com dicas e showcase.</p>
      dev:
        title: Desenvolvimento
        text: |
              <p>Quer participar do desenvolvimento? Então cadastre-se no <a href="http://github.com">Github</a> e crie logo o seu fork.</p>