name: Novo SGA
markdown: redcarpet
pygments: true
locale: pt
locales: 
    pt:
        meta:
            description: "Novo SGA: Sistema de Gerenciamento de Atendimento gratuido e código aberto"
            keywords: novo, sga, sistema, gerenciamento, atendimento, controle, fila, senha, emissao, impressao, gratis, gratuito, open-source, web
            author: Rogério Alencar Lino Filho
        nav:
            home: Home
            projects: Projetos
            downloads: Downloads
            faq: FAQ
            community: Comunidade
            about: Sobre
        home:
            title: Novo, rápido e moderno!
            text: Sistema de Gerenciamento de Atendimento de código aberto e gratuito.
            see_more: Ver mais
            about:
                title: Sobre
                text: Novo SGA não é um simples projeto e sim uma plataforma para gerenciamento de filas de atendimento.
            projects:
                title: Projetos
                text: Conheça os projetos que fazem parte da plataforma Novo SGA.
            support:
                title: Suporte
                text: Dúvidas? Visite a seção FAQ do site, ou acesse um dos canais de comunicação da comunidade.
            donation:
                title: Doação
                text: Ajude a manter o desenvolvimento do projeto. Faça uma doação
            news:
                title: Novidades
                text: Veja abaixo as últimas notícias do blog e os últimos comentários do fórum
        downloads:
            title: Downloads
            text: |
                  <p>A partir da versão 1.0.0 os componentes Desktops (Java/JavaFX) não são mais compatíveis com o Novo SGA. No lugar destes, você pode usar as implementações em HTML.</p>
                  <p>Então caso, queira utilizar ou esteja utilizando uma implementação Desktop, opte por baixar uma das versões 0.X.X.</p>
            last:
                title: Última versão estável
                text: |
                      <p>Baixe agora a última versão estável através do nosso repositório no Github.</p>
                novosga: |
                         <p>Projeto principal.</p>
                painelweb: |
                           <p>Painel escrito em HTML5 e Javascript.</p>
                triagemtouch: |
                              <p>Triagem voltada para telas sensíveis ao toque.</p>
            others:
                title: Outras versões
                text: |
                      <p>Versões anteriores (até 0.7.2). Pacotes disponíveis: novosga-web, novosga-painel-client (PainelFX) e novosga-painel-server.</p>
                version: Versão
                painelfx: Painel Cliente (PainelFX)
                server: Painel Servidor
            demo:
                title: Demonstração
                text: |
                      <p>Versão de desenvolvimento disponível online através do link: <a href="http://novosga.org/demo">http://novosga.org/demo</a></p>
                user: Usuário
                pass: Senha
                
        projects:
            title: Projetos
            download: Download
            view: Visitar
            novosga:
                text: |
                      <p>Projeto principal, divido em módulos.</p>
                      <p>Módulos principais (pré-instalados):</p>
                      <ul>
                          <li>Triagem (emissão de senha)</li>
                          <li>Monitor (gerenciamento)</li>
                          <li>Atendimento</li>
                      </ul>
            painelweb:
                text: |
                      <p>Implementação do painel de exibição de senhas escrito em HTML5 e Javascript.</p>
                      <p>Compatível com versões do Novo SGA a partir da 1.0.0</p>
            triagemtouch:
                text: |
                      <p>Implementação da Triagem para auto-atendimento em telas sensíveis ao toque.</p>
                      <p>Compatível com versões do Novo SGA a partir da 1.0.0</p>
            painelfx:
                text: |
                      <p>Implementação do painel de exibição de senhas escrito em JavaFX (JRE1.7+). Depende do servidor de painel para funcionar.</p>
                      <p>Compatível até a versão 0.7.2 do Novo SGA.</p>
            painelserver:
                text: |
                      <p>Processo escrito em Java para disparar as senhas via UDP ou TCP para os painéis (desktop) cadastrados.</p>
                      <p>Compatível até a versão 0.7.2 do Novo SGA.</p>
                            
        about:
            title: Sobre
            text: |
                  <p>SGA é o acrônimo de Sistema de Gerenciamento de Atendimento, e Novo SGA é uma plataforma de código aberto que permite grandes ou pequenas organizações gerenciarem o fluxo do atendimento.</p>
                  <p>Criado em Dezembro de 2012 por <a href="http://rogeriolino.com">Rogério Alencar Lino Filho</a>, o Novo SGA provê funcionalidades para controlar a ordem da fila e os tempos de atendimento (hora de chegada, tempo de espera, tempo de deslocamento até o balcão e tempo de atendimento), além de fornecer gráficos e estatísticas para aprimorar o atendimento ao cliente.</p>
            features:
                title: Funcionalidades
                text: |
                      <ul>
                          <li>Emissão de senhas normais ou prioritárias</li>
                          <li>Cancelamento, reativação e transferência de senha</li>
                          <li>Configuração de tipo de atendimento por guichê</li>
                          <li>Monitoramento das filas por serviços</li>
                          <li>Númeração incremental por sigla de serviço ou global</li>
                          <li>Gráficos e relatórios</li>
                      </ul>
            screenshots:
                title: Screenshots
                prints: 
                    - PainelFX
                    - PainelFX - Screensaver
                    - PainelFX - Configuração
                    - PainelFX - Configuração
                    - Login
                    - Escolhendo unidade
                    - Página Inicial
                    - Perfil do usuário
                    - Configuração da Unidade
                    - Configuração da Unidade
                    - Triagem
                    - Triagem
                    - Monitor de senhas
                    - Monitor de senhas
                    - Monitor de senhas
                    - Atendimento
                    - Atendimento
                    - Atendimento
                    - Atendimento
                    
        community:
            title: Comunidade
            text: |
                  <p>Ajuda a comunidade do Novo SGA continuar crescendo. Participe nos canais de comunicação e faremos um sistema cada vez melhor.</p>
            view: Visite
            blog:
                title: Blog
                text: |
                      <p>Fique sabendo das novidades sobre o Novo SGA através do blog do projeto.</p>
                      <p>A partir dele publicamos as notícias sobre versões lançadas, versões futuras e dicas.</p>
            forum:
                title: Fórum
                text: |
                      <p>Tire suas dúvidas, ou ajude a sanar as dúvidas de outros usuários, nos fóruns dos projetos ou contribua com dicas e showcase.</p>
            dev:
                title: Desenvolvimento
                text: |
                      <p>Quer participar do desenvolvimento? Então cadastre-se no <a href="http://github.com">Github</a> e crie logo o seu fork.</p>
            donation:
                title: Doação
                text: |
                      <p>Quer ajudar a manter os projetos e não sabe como contribuir? Faça uma doação:</p>

        faq:
            title: FAQ
            text: |
                  <p>Seção com algumas das perguntas feitas frequentemente.</p>
                  <p>Caso não encontre sua dúvida aqui, sinta-se à vontade para publicá-la no <a href="http://novosga.org/forum">nosso fórum</a>.</p>
            entries:
                - title: O Novo SGA funciona no Windows?
                  text: |
                          <p>Sim. O Novo SGA é escrito em PHP e Java, que são linguagens multiplataformas.</p>
                          <p>Porém, a documentação do Novo SGA é focada em distribuíções Linux baseadas em Debian.</p>
                - title: Qual distribuição Linux devo utilizar?
                  text: |
                          <p>Qualquer distribuíção que tenha suporte à instalação do PHP 5.3+ e Java 7.</p>
                          <p>Porém, a documentação do Novo SGA é focada em distribuíções Linux baseadas em Debian.</p>
                - title: Quais os requisitos de hardware para instalar o Novo SGA?
                  text: |
                          <p>Definir os requisitos mínimos de hardware para sustentar o sistema depende de vários fatores, como por exemplo o tamanho da instituição, a quantidade de unidades de atendimento e de usuários, número de acessos simultâneos, volume de atendimento e etc.</p>
                - title: Existe alguma forma de imprimir direto sem escolher a impressora?
                  text: |
                          <p>Isso varia de acordo com o navegador que esteja utilizando.</p>
                          <p><strong>Firefox</strong><p>
                          <p>No firefox há uma opção chamada "silent print".</p>
                          <ol>
                                <li>Acesse a página <a href="about:config">about:config</a></li>
                                <li>clique com o botão direito em qualquer lugar da página e selecione "Novo->Booleano".</li>
                                <li>digite o nome "print.always_print_silent"</li>
                                <li>selecione o valor "verdadeiro" (true)</li>
                          </ol>
                          <p><strong>Chrome 18+</strong><p>
                          <p>No chrome pode imprimir silenciosamente utilizando a opção kiosk. Basta adicionar os parâmetros "--kiosk --kiosk-printing" no atalho do navegador</p>
                          <ul>
                                <li>Linux: google-chrome --kiosk --kiosk-printing</li>
                                <li>Windows: botão direito no atalho, propriedades, e adicionar os parâmetros (--kiosk --kiosk-printing) ao final do campo alvo.</li>
                          </ul>
                - title: Qual é o modelo de impressora recomendado?
                  text: |
                          <p>Qualquer impressora térmica.</p>
                - title: Estou tendo problemas com a codificação dos caracteres. O que pode ser?
                  text: |
                          <p>O encoding utilizado pelo Novo SGA é o UTF-8.</p>
                          <p>O que pode estar acontecendo é que o banco de dados (banco ou tabela) não em UTF-8.</p>
                          <p><strong>MySQL</strong></p>
                          <p>Se você estiver utilizando o MySQL, verifique se o arquivo my.conf está configurado como mostra abaixo:</p>
                          <pre>[client]
                          ...
                          default-character-set = utf8

                          [mysqld]
                          ...
                          character-set-server = utf8</pre>
                - title: Erro "Falha obtendo unidades". O que pode ser?
                  text: |
                          <p>A principal razão para não conseguir obter unidades é causada por erros de configuração (server.conf) do controlador de paineis.</p>
                          <p>Sugiro que revisem com cuidado esse arquivo, atentando para todos os detalhes. Os comentários contidos nesse arquivo devem ser lidos e entendidos para que não hajam equívocos.</p>
                          <p>Também devem ser considerados outros problemas alheios ao sistema, como problemas de rede, firewall etc.</p>
                          <p>Problemas com bloqueio por proxy também já foram relatados.</p>
                - title: Como alterar a palavra "Guichê" que aparece no painel?
                  text: |
                          <p><strong>Para versões até 0.7.2</strong></p>
                          <p>Abra o arquivo <strong>core/business/AtendimentoBusiness.php</strong>, procure por <strong>nm_local</strong>, e altere o valor desse parâmetro para o nome desejado.</p>
                          <p>No caso abaixo, ao invés de "Guichê" aparecerá "Sala":</p>
                          <pre>
                          // Antes
                          $stmt->bindValue('nm_local', _('Guichê'));</pre>
                          <pre>
                          // Depois
                          $stmt->bindValue('nm_local', _('Sala'));</pre>
                - title: Apareceu mensagem de nova versão disponível. Como atualizo o Novo SGA?
                  text: |
                          <p>Primeiramente é bom acessar o <a href="http://novosga.org/blog" title="Blog">blog do Novo SGA</a> para saber quais mudanças foram feitas. Como o sistema é dividido em 3 partes, nem sempre as 3 sofrem anterações. Depois basta ir à <a href="http://novosga.org/download">página de download</a> e baixar a nova versão</p>
                          <p><strong>Atualizando o Painel</strong></p>
                          <p>Para atualizar o painel (tanto cliente quanto servidor) basta apenas parar o processo e substituir os arquivos pela nova versão.</p>
                          <p><strong>Atualizando a parte Web</strong></p>
                          <p>Já na parte web, é necessário manter o arquivo de configuração atual. Para isso basta seguir os passos:</p>
                          <ul>
                                <li>Extraia a versão web em um novo diretório</li>
                                <li>Substitua o arquivo core/Config.php pelo o mesmo arquivo da versão já instalada</li>
                                <li>Teste a nova versão e depois substitua a antiga pela nova. Pronto.</li>
                          </ul>
